### ISSUE TITLE
Remove all relative references to pogobuf

### ISSUE THREAD

**Issue by netfusion** [nicoschmitt/pogonode#5]
Included as a nodejs module all `require('../pogobuf')` calls will fail because the files itsself are executed from within the `bin` subdirectory.
To fix this change all these includes to simple module references: `require('pogobuf')`.
Use `package.json` to change the reference if nessesary...

**Comment by niicojs** [comment]
I know about this. The thing is pogonode itself was made for me to test when working on pogobuf, thats why on my pc there is a pogobuf folder sync with git.
I'll have to think of a way to make this work :)

**Comment by niicojs** [comment]
fixed on master, I'm using dev for my work then
